title: Iarley Pereira Lobo
description: Theoretical physicist working on quantum gravity phenomenology, gravitational waves, black holes and deviations from Riemannian geometry.
url: "https://iarleyplobo.github.io"
baseurl: ""
markdown: kramdown
permalink: pretty
